version: "3"
volumes:
  dpsms_db:
services:
  dpsms_db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - dpsms_db:/var/lib/postgresql/data # save data between restarts
    ports:
      - "2429:5432"
